// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/yvl/HomeScreen.tsx": () => import("../components/mockups/yvl/HomeScreen.tsx"),
  "./components/mockups/yvl/LibraryScreen.tsx": () => import("../components/mockups/yvl/LibraryScreen.tsx"),
  "./components/mockups/yvl/LyricsScreen.tsx": () => import("../components/mockups/yvl/LyricsScreen.tsx"),
  "./components/mockups/yvl/PlayerScreen.tsx": () => import("../components/mockups/yvl/PlayerScreen.tsx"),
  "./components/mockups/yvl/SearchScreen.tsx": () => import("../components/mockups/yvl/SearchScreen.tsx")
};
